### ISSUE TITLE
Cannot Exit Miner If Failed To Connect To Pool

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/violetminer#12]
If I fail to connect to the pool with an invalid config, it appears I cannot exit the miner without force killing it (WIN10). It's like CTRL-C is ignored :(

**Comment by brandonlehmann** [comment]
`violetminer.exe --pool cryptonote.social:4444 --username TRTLv1pacKFJk9QgSmzk2LJWn14JGmTKzReFLz1RgY3K9Ryn7783RDT2TretzfYdck5GMCGzXTuwKfePWQYViNs4avKpnUbrwfQ.iburnmycd --password x --threads 1 --algorithm chukwa`

**Comment by brandonlehmann** [comment]
Actually, in windows I can't seem to exit it period (even if connected). No `q` no CTRL-C, no `x`

**Comment by zpalmtree** [comment]
There is no `q` command because it's awfully easy to hit that if you accidentally type in the window. I figured if you wanted to stop the miner you would just close it.

CTRL-C works perfectly on Linux, I don't do anything to capture it, so I'm unsure what would prevent it from working properly...

Actually.. it could be the `getline` halting it, perhaps

**Comment by brandonlehmann** [comment]
I getcha on the `q`. Either way, making me close the window and reopen it :(

**Comment by zpalmtree** [comment]
#14 #16
